databases:
  - name: render_dot_com__rails_tutorial
    databaseName: render_dot_com__rails_tutorial
    user: render_dot_com__rails_tutorial

services:
  - type: web
    name: render_dot_com__rails_tutorial
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_dot_com__rails_tutorial
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

